# Generated by Django 4.1.1 on 2022-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem1',
            field=models.ImageField(null=True, upload_to='locator/upload/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem2',
            field=models.ImageField(null=True, upload_to='locator/upload/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem3',
            field=models.ImageField(null=True, upload_to='locator/upload/%Y/%m/%d/'),
        ),
    ]
