# Generated by Django 4.1.2 on 2022-11-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0010_remove_post_status_post_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
