# Generated by Django 4.1.2 on 2022-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0011_rename_author_post_user_rename_author_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
