# Generated by Django 4.1.2 on 2022-11-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0012_post_city_post_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
